name: Build and Push to GCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Container
      run: dotnet publish /home/runner/work/mldas/mldas/MLDAS.Web/MLDAS.Web.csproj -r linux-x64 /t:PublishContainer -c Release

    - name: Tag Container
      run: docker tag mldas-web:latest us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/mldas/mldas/mldas-web

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v2
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'
        credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}"
    - name: Login to GAR
      uses: docker/login-action@v3
      with:
       registry: us-central1-docker.pkg.dev
       username: oauth2accesstoken
       password: ${{ steps.auth.outputs.access_token }}
       
    - name: Push Container to GCP
      run: docker push us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID}}/mldas/mldas/mldas-web
